### ISSUE TITLE
配置文件删去RESTful导致恐慌

### ISSUE THREAD

**Issue by Fhokud** [Itsusinn/tuic#28]
```rust
24-10-26 10:42:12  INFO tuic_server::connection::handle_task: [0x4ae4d9d0] [[::ffff:192.168.2.5]:43370] [2690a853-248d-4672-8ef2-31d0f8d25a79] [TCP] 173.194.202.188:5228
thread 'tokio-runtime-worker' panicked at .cargo\registry\src\index.crates.io-6f17d22bba15001f\lateinit-0.2.1\src\lib.rs:77:13:
LateInit used without initialization
stack backtrace:
   0:     0x7ff668cc7d53 - std::backtrace_rs::backtrace::dbghelp64::trace::ha37491dffc48a830
                               at /rustc/798fb83f7d24e31b16acca113496f39ff168c143\library/std\src\..\..\backtrace\src\backtrace/dbghelp64.rs:91:5
   1:     0x7ff668cc7d53 - std::backtrace_rs::backtrace::trace_unsynchronized::h00196f4c8773cffd
                               at /rustc/798fb83f7d24e31b16acca113496f39ff168c143\library/std\src\..\..\backtrace\src\backtrace/mod.rs:66:5
   2:     0x7ff668cc7d53 - std::sys::backtrace::_print_fmt::h1bf039b84667ae55
                               at /rustc/798fb83f7d24e31b16acca113496f39ff168c143\library/std\src\sys/backtrace.rs:66:9
   3:     0x7ff668cc7d53 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h76f53414ab42d4b4
                               at /rustc/798fb83f7d24e31b16acca113496f39ff168c143\library/std\src\sys/backtrace.rs:39:26
   4:     0x7ff668d1400a - core::fmt::rt::Argument::fmt::he1c59dbeb6f94aa4
                               at /rustc/798fb83f7d24e31b16acca113496f39ff168c143\library/core\src\fmt/rt.rs:177:76
   5:     0x7ff668d1400a - core::fmt::write::hf7c712e67c3a661c
                               at /rustc/798fb83f7d24e31b16acca113496f39ff168c143\library/core\src\fmt/mod.rs:1186:21
   6:     0x7ff668cbdda2 - std::io::Write::write_fmt::h1593a125e3cfca9b
                               at /rustc/798fb83f7d24e31b16acca113496f39ff168c143\library/std\src\io/mod.rs:1839:15
   7:     0x7ff668cc7bc5 - std::sys::backtrace::BacktraceLock::print::h706932dc957eccbc
                               at /rustc/798fb83f7d24e31b16acca113496f39ff168c143\library/std\src\sys/backtrace.rs:42:9
   8:     0x7ff668cca406 - std::panicking::default_hook::{{closure}}::hf1ce053c0b36617a
                               at /rustc/798fb83f7d24e31b16acca113496f39ff168c143\library/std\src/panicking.rs:268:22
   9:     0x7ff668cca215 - std::panicking::default_hook::hae0272eb2459308d
                               at /rustc/798fb83f7d24e31b16acca113496f39ff168c143\library/std\src/panicking.rs:295:9
  10:     0x7ff668ccabbb - std::panicking::rust_panic_with_hook::hb8f8846cf8cd29b9
                               at /rustc/798fb83f7d24e31b16acca113496f39ff168c143\library/std\src/panicking.rs:801:13
  11:     0x7ff668ccaa1b - std::panicking::begin_panic_handler::{{closure}}::haa1888a24b52539c
                               at /rustc/798fb83f7d24e31b16acca113496f39ff168c143\library/std\src/panicking.rs:667:13
  12:     0x7ff668cc859f - std::sys::backtrace::__rust_end_short_backtrace::h749630f251dce9be
                               at /rustc/798fb83f7d24e31b16acca113496f39ff168c143\library/std\src\sys/backtrace.rs:170:18
  13:     0x7ff668cca6ce - rust_begin_unwind
                               at /rustc/798fb83f7d24e31b16acca113496f39ff168c143\library/std\src/panicking.rs:665:5
  14:     0x7ff668d10361 - core::panicking::panic_fmt::h3601c2326738ec35
                               at /rustc/798fb83f7d24e31b16acca113496f39ff168c143\library/core\src/panicking.rs:74:14
  15:     0x7ff668d103fd - core::panicking::panic::h12864df67bedca8e
                               at /rustc/798fb83f7d24e31b16acca113496f39ff168c143\library/core\src/panicking.rs:148:5
  16:     0x7ff66830d686 - tuic_server::restful::traffic_tx::h9c063ca3e55b2414
  17:     0x7ff668151d44 - tuic_server::connection::handle_task::<impl tuic_server::connection::Connection>::handle_connect::{{closure}}::{{closure}}::he324a346ec7a45b8
  18:     0x7ff66814f759 - tuic_server::connection::handle_task::<impl tuic_server::connection::Connection>::handle_connect::{{closure}}::h4bd440833ca59e7e
  19:     0x7ff6680d96fc - tuic_server::connection::handle_stream::<impl tuic_server::connection::Connection>::handle_bi_stream::{{closure}}::ha1bfcabec0a6da1d
  20:     0x7ff66818e492 - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h5ea735f1a53f78e6
  21:     0x7ff66818b654 - tokio::runtime::task::core::Core<T,S>::poll::h471ec0f2ee06189c
  22:     0x7ff668327986 - tokio::runtime::task::harness::poll_future::{{closure}}::hd2ae07ecad2b8e40
  23:     0x7ff6681feab1 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb977a62e91e2879d
  24:     0x7ff668311416 - std::panicking::try::do_call::h1c2ef3d83cef7b83
  25:     0x7ff6682f4f98 - __rust_try
  26:     0x7ff6682f2b4e - std::panic::catch_unwind::hbbcf616ae75a3778
  27:     0x7ff668322674 - tokio::runtime::task::harness::poll_future::habda6a6f866237c9
  28:     0x7ff66832b3dc - tokio::runtime::task::harness::Harness<T,S>::poll_inner::hdca828af55ddb902
  29:     0x7ff668332613 - tokio::runtime::task::harness::Harness<T,S>::poll::ha1af31851f0528a7
  30:     0x7ff6682b5a81 - tokio::runtime::task::raw::poll::h190c54d7abb0a9fc
  31:     0x7ff668918ae1 - tokio::runtime::task::raw::RawTask::poll::h3a598eef7c3a7aac
  32:     0x7ff66893d258 - tokio::runtime::task::LocalNotified<S>::run::h66d47060cc80fa7c
  33:     0x7ff66897fb8c - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}::hd5e0b1b33c1dbc45
  34:     0x7ff66897fa0b - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hd5b65b58bd5b4e44
  35:     0x7ff66897f128 - tokio::runtime::scheduler::multi_thread::worker::Context::run::hfcd6dabcd1d62792
  36:     0x7ff66897edd4 - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}::hc894ec1c68809e2b
  37:     0x7ff66899caf4 - tokio::runtime::context::scoped::Scoped<T>::set::h6ee2d57f0e74a489
  38:     0x7ff668965625 - tokio::runtime::context::set_scheduler::{{closure}}::he2ffb0b6ab4ffc95
  39:     0x7ff668936baa - std::thread::local::LocalKey<T>::try_with::h2cf08fdd21d6b2fa
  40:     0x7ff6689364c9 - std::thread::local::LocalKey<T>::with::hc621ef24f2f7489f
  41:     0x7ff6689655a4 - tokio::runtime::context::set_scheduler::h53ca481320f643ee
  42:     0x7ff66897ecef - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::h99b9055dcc459d3c
  43:     0x7ff66896fe89 - tokio::runtime::context::runtime::enter_runtime::h2533d49a18d1cc0c
  44:     0x7ff66897ead7 - tokio::runtime::scheduler::multi_thread::worker::run::hc7a58168ea62fea2
  45:     0x7ff66897e819 - tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}::h46ad064f563e6760
  46:     0x7ff668948135 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h3ce0900ec74a2e97
  47:     0x7ff6689c19e2 - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::hf66e501b3dbc5ec0
  48:     0x7ff6689beed4 - tokio::runtime::task::core::Core<T,S>::poll::h41802cd986684c61
  49:     0x7ff668906f96 - tokio::runtime::task::harness::poll_future::{{closure}}::h615dba65123b2eaa
  50:     0x7ff66890e681 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hfc5b9197af484986
  51:     0x7ff668969456 - std::panicking::try::do_call::h31fe0279d02c115a
  52:     0x7ff6689aa5c8 - __rust_try
  53:     0x7ff6689a683e - std::panic::catch_unwind::h6c02b242e46b2474
  54:     0x7ff668904204 - tokio::runtime::task::harness::poll_future::h8c3c6b01e6a92c31
  55:     0x7ff6688f77ec - tokio::runtime::task::harness::Harness<T,S>::poll_inner::h324fc6dbc3de591d
  56:     0x7ff6688f6873 - tokio::runtime::task::harness::Harness<T,S>::poll::h6849a8fa30700301
  57:     0x7ff668918e31 - tokio::runtime::task::raw::poll::h4f87d6828b5c79d8
  58:     0x7ff668918ae1 - tokio::runtime::task::raw::RawTask::poll::h3a598eef7c3a7aac
  59:     0x7ff66893d317 - tokio::runtime::task::UnownedTask<S>::run::he11f4f4dab89f7ba
  60:     0x7ff668952869 - tokio::runtime::blocking::pool::Task::run::h311cae6951504a67
  61:     0x7ff66895d47b - tokio::runtime::blocking::pool::Inner::run::h1760e4947f3548a7
  62:     0x7ff66895d1d2 - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::h38bebba7619bc32a
  63:     0x7ff6689a4a79 - std::sys::backtrace::__rust_begin_short_backtrace::ha4b1e12e866a93db
  64:     0x7ff668961031 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h1930a9bba62f77de
  65:     0x7ff66890df81 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h944c0d5e9314b7cd
  66:     0x7ff66896a921 - std::panicking::try::do_call::hf34ed24efaa78c47
  67:     0x7ff668968a58 - __rust_try
  68:     0x7ff668960e7d - std::thread::Builder::spawn_unchecked_::{{closure}}::hd2316e0c2b3430a0
  69:     0x7ff668923ff9 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he9b925f57a884629
  70:     0x7ff668cda4ad - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h44739fd58e39988e
                               at /rustc/798fb83f7d24e31b16acca113496f39ff168c143\library/alloc\src/boxed.rs:2454:9
  71:     0x7ff668cda4ad - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h78b8dfdba04c37ff
                               at /rustc/798fb83f7d24e31b16acca113496f39ff168c143\library/alloc\src/boxed.rs:2454:9
  72:     0x7ff668cda4ad - std::sys::pal::windows::thread::Thread::new::thread_start::hd18bac14c1089ea3
                               at /rustc/798fb83f7d24e31b16acca113496f39ff168c143\library/std\src\sys\pal\windows/thread.rs:55:22
  73:     0x7ff949e4dbe7 - <unknown>
  74:     0x7ff94b705a4c - <unknown>
thread 'tokio-runtime-worker' panicked at .cargo\registry\src\index.crates.io-6f17d22bba15001f\lateinit-0.2.1\src\lib.rs:77:13:
LateInit used without initialization
```

**Comment by Itsusinn** [comment]
really？

**Comment by Itsusinn** [comment]
> I also found that Linux was actually Ctrl+C was tricky to exit, so I had to kill the process.

Thats normal.

**Comment by Itsusinn** [comment]
> yeap 
> After deleting [restful] in its entirety

Can you send your config?

**Comment by Itsusinn** [comment]
try v1.3.2
