### ISSUE TITLE
bug ExportKeyingMaterialError

### ISSUE THREAD

**Issue by eqfae** [Itsusinn/tuic#34]
```
Mon Nov 25 19:34:04 2024 daemon.err tuic-client[12201]: thread 'tokio-runtime-worker' panicked at tuic-quinn/src/lib.rs:578:14:
Mon Nov 25 19:34:04 2024 daemon.err tuic-client[12201]: called `Result::unwrap()` on an `Err` value: ExportKeyingMaterialError
Mon Nov 25 19:34:04 2024 daemon.err tuic-client[12201]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Mon Nov 25 19:48:17 2024 daemon.err tuic-client[12201]: thread 'tokio-runtime-worker' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/quinn-proto-0.11.8/src/connection/mod.rs:3357:14:
Mon Nov 25 19:48:17 2024 daemon.err tuic-client[12201]: only called for `Data` packets
Mon Nov 25 19:48:17 2024 daemon.err tuic-client[12201]: thread 'tokio-runtime-worker' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/quinn-0.11.5/src/mutex.rs:140:42:
Mon Nov 25 19:48:17 2024 daemon.err tuic-client[12201]: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
Mon Nov 25 19:48:17 2024 daemon.err tuic-client[12201]: stack backtrace:
```
![图片](https://github.com/user-attachments/assets/10262856-f3e2-41de-a001-d4f6b1f26112)
崩溃了 ssh手动重启tuic服务才好

**Comment by Itsusinn** [comment]
这是启动时发生错误还是运行时发生的？

**Comment by eqfae** [comment]
![图片](https://github.com/user-attachments/assets/94a9c70f-d368-485e-87f9-b8ce999d6647)
运行时 昨天也有 开的 用的自签名

**Comment by Itsusinn** [comment]
能贴一下完整的客户端和服务端的配置吗，我复现不出来

**Comment by eqfae** [comment]
https://github.com/Itsusinn/tuic/issues/21 有配置
是偶尔出现 1天未必有一次

**Comment by eqfae** [comment]
中间人攻击导致的密码错误? 0rtt拿着连接被丢包前的已验证过可信证书非对称加密协商的对称密码 连上了的中间人伪装的服务端
看到过一种代理工具 不用可信证书 直接服务器拿公钥 客户端拿私钥 目前非对称加密 破解难度很高 即使未来被破解相信也会有更强的 只要历史还在重复

**Comment by Itsusinn** [comment]
可能是有东西在攻击tuic的这个udp端口，攻击器构造了一个特殊的udp包（很可能是无意的）让tuic panic

**Comment by Itsusinn** [comment]
目前加了个临时解决方法，不会panic了，但还是需要找到根本原因
